### ISSUE TITLE
RSS Aggregation System

### ISSUE THREAD

**Issue by DannyBrown-xx** [csblogs/csblogs#24]
The RSS aggregation should work if we complete the following stages:

(If you have comments or questions about individual stages please comment on that issue. If you have comments or questions about the overall system please comment here)
- [*] Write Node.js prototype which can be run from Microsoft Azure Website WebJobs (See: http://www.hanselman.com/blog/IntroducingWindowsAzureWebJobs.aspx and http://odetocode.com/blogs/scott/archive/2014/04/07/azure-webjobs-with-node-js.aspx) Our system should be triggered every 5 - 10 minutes (this is changed through the Azure Portal, so I'll have to do that bit) (Issue: #25)

All further points take place inside the WebJob. Please bare in mind that WebJobs are sandboxed from the website itself and therefore cannot call any website code. 
- [] Link up the WebJob with the MongoDB database (Issue: #26)
- [] Retrieve list of feed URLs from MongoDB (Issue: #27)
- [] Request data from all the Feeds URLs from the DB (this can be async or synchronous, doesn't matter as no one is directly waiting on it, but preferable async). Remember that feeds can either be RSS or ATOM -- correctly parsing both ATOM and RSS could be a project in itself -- so lets use a node package to deal with the actual parsing of the feed. (Issue: #28)

_Some people have asked why we intend to download and store blog posts. Its so that we don't have to request the RSS of every blog each time a visitor requests a page. Doing so would mean we'd have a really slow page load. So we store them ahead of time. Getting them from the database is much quicker!_
- [] Determine if any of the articles in the RSS feeds are new (Issue: #30)
- [] Add new articles to a MongoDB table of Blog posts, substituting in foreign keys for the correct author, rather than the Author name provided in RSS. (Issue: #31)

**Comment by apringle** [comment]
+1 to the WebJob, preferably this would be callable from a development node instance (and written in a way that is somewhat portable)

**Comment by apringle** [comment]
If determining if articles are new is non trivial we could fetch and store the last 10 articles removing any existing entries and move the aggregation of articles to a later task

**Comment by DannyBrown-xx** [comment]
@apringle I think the code we write can be completely portable. If we ever wanted to change host we could just create a cron job, or similar.

Agreed. We can start of with the simple approach if need be.

**Comment by Godley** [comment]
@DannyBrown I think all of this needs better explaining. You and pringle seem to get it, but looking at the web job thing I get roughly that it fires _something_ in a similar way to a cron job would but for azure, but what it's expected to fire I have no clue - is it intended to fire the rest of the points in this issue? I probably need to read up a little bit on it I guess.
So I looked at the next step. still not sure.
third step I think is self explanatory to anyone with reasonable web dev knowledge because it's just a query. Fourth Fifth and sixth points are fine.
